"""Initial migration.

Revision ID: 7c006171d6c9
Revises: 
Create Date: 2022-05-22 23:51:47.192743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c006171d6c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('hpsw', sa.String(length=500), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('author', sa.String(length=25), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('Likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['Users.username'], ),
    sa.ForeignKeyConstraint(['video_id'], ['Videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Likes')
    op.drop_table('Videos')
    op.drop_table('Users')
    # ### end Alembic commands ###
